# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kyvDUI1vYnNxYY0SPnHJB1xbiO2LwSq
"""

import math

print(math.pi)

print('Hello,world!') #imprimir texto

print("""
oi
1
2
3
""")# imprimir texto mais de uma linha

nome = 'Dalmo'
idade = 18
tamanho = 1.80
is_studente = True

print(nome)
print(idade)
print(tamanho)
print(is_studente)

print(f"Nome: {nome}")
print(type(str(tamanho)))

a = 10+5
b = 5-2
c= 8/4
d = 9*9


print(f'a = {a}, b = {b}, c = {c}, d = {d}')

print( 10 > 5)
print(9 == 8)
print(9 != 8)

if a > 5:
    print(' é maior que 5')
elif a < 5:
  print(' é menor que 5')
  print(' é igual a 5')

for i in range(5):
  print(i)

x=0
while x<10:
  print(x)
  x+=1

def somar_numero(a,b):
  return a+b

print(somar_numero(20,50))

idade = [1,2,3,4,5,6,7]
altura = []

print(idade[4])
print(altura)

altura.append(1.70)

print(altura)

altura.remove(1.5)
print(altura)

num1 = int(input('Digite'))
num2 = int(input('Digite'))

print(type(num1))
print(type(num2))

aluno = [{
    "nome": "Ana",
    "idade": 20,
    "curso": "Cien. computação",
    "Matricula": "000.00.154"
},
{
    "nome": "Ana",
    "idade": 28,
    "curso": "Cien. computação",
    "Matricula": "000.00.154"
},
{
    "nome": "Ananda",
    "idade": 20,
    "curso": "Cien. computação",
    "Matricula": "000.00.554"

         }]

print(aluno)
print(aluno[0]['idade'])

for item in aluno:
  if item['nome'] == "Ana":
    print(f"Nome: {item}")

